<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.zys.railway_12306</groupId>
        <artifactId>railway_12306</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>frameworks</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>base-spring-boot-starter</module>
        <module>bizs-spring-boot-starter</module>
        <module>bizs-spring-boot-starter</module>
        <module>cache-spring-boot-starter</module>
        <module>common-spring-boot-starter</module>
        <module>convention-spring-boot-starter</module>
        <module>database-spring-boot-starter</module>
        <module>designpattern-spring-boot-starter</module>
        <module>distributedid-spring-boot-starter</module>
        <module>idempotent-spring-boot-starter</module>
        <module>log-spring-boot-starter</module>
        <module>web-spring-boot-starter</module>
    </modules>

</project>
